Using redux
Flavioasjr/Shopping-Cart pull request #1
Opened 2022-07-20 12:46 UTC by Flavioasjr

2022-07-20 13:10 UTC, kaueburiti requested changes
No geral está tudo surpreendentemente bem feito 👏🏾 
Porém sugeri algumas melhorias

2022-07-20 13:10 UTC, kaueburiti commented on build/asset-manifest.json
> -    "main.js": "/Shopping-Cart/static/js/main.efbd505e.js",
Todo essa pasta `build` deveria ser adicionada no `.gitignore` (você sabe para que ele serve?).
Não é do nosso interesse revisar ou versionar o que é gerado dentro dessa pasta.

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsDataSlice.js
> +import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
Parabéns por já iniciar com o redux toolkit 👏🏾 
Normalmente eu peço para a pessoa iniciar com o redux puro, o que levou você a começar já com o toolkit?

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsDataSlice.js
> +      (product) => product.category !== 'electronics'
Qual a razão de não poder ter items da categoria electronics?

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsDataSlice.js
> +  name: 'productsData',
você poderia chamar isso apenas de `products` ;)

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsDataSlice.js
> +  extraReducers(builder) {
Excelente! Tu realmente entendeu isso aqui ou só fez copiando?

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsInCartSlice.js
> +    productAdded: {
um nome melhor para essas ações seria algo como `addProduct`, `removeProduct`. 

lembre-se que você quer descrever a ação e não descever o que foi feito

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsInCartSlice.js
> +        const productExists = state.some(
o nome dessa variável está incompleto, fica parecendo que ela define se o produto existe ou não, mas o que ela define é se o produto já está no carrinho ou não

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsInCartSlice.js
> +      prepare(product) {
para que serve esse prepare? eu estou por fora 🤔

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsInCartSlice.js
> +      prepare(product) {
aaaah isso é só masi um reducer/action  né?

2022-07-20 13:10 UTC, kaueburiti commented on src/features/productsInCartSlice.js
> +      // return state.filter((product) => product.quantity > 0);
remover comentário

2022-07-20 13:10 UTC, kaueburiti commented on src/features/shoppingCartIsShowSlice.js
> +  name: 'shoppingCartIsShow',
um nome melhor poderia ser "shouldShowShoppingCart"

2022-07-20 13:10 UTC, kaueburiti commented on src/components/ListShoppingCart/ListShoppingCart.js
> +                      onClick={() =>
o ideal seria você criar uma funcão e passar aqui, em vez de deixar desse modo

2022-07-20 13:10 UTC, kaueburiti commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
Utilize CSS variables em vez disso: https://developer.mozilla.org/pt-BR/docs/Web/CSS/Using_CSS_custom_properties

2022-07-20 13:10 UTC, kaueburiti commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
O mesmo se aplica a todos lugares abaixo

2022-07-20 20:31 UTC, Flavioasjr commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
Entendi. Eu já usei CSS variables em outros projetos, só usei dessa forma porque se tem varios arquivos 'styled', aí se quiser modificar a cor base do projeto, bastaria mudar no arquivo 'color.js'.

2022-07-20 20:31 UTC, Flavioasjr commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
Seria melhor usar CSS variables mesmo?

2022-07-20 20:33 UTC, Flavioasjr commented on src/components/ListShoppingCart/ListShoppingCart.js
> +                      onClick={() =>
Então toda vez que tiver uma ação de um usuário, e usar o dispatch, é melhor criar uma função do que mandar o dispatch diretamente?

2022-07-20 20:44 UTC, kaueburiti commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
confesso que não entendi. só é você criar um arquivo com css variables globais 🤔

2022-07-20 20:44 UTC, kaueburiti commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
https://codesandbox.io/s/css-variables-with-styled-components-1q887

2022-07-20 20:44 UTC, kaueburiti commented on src/components/ListShoppingCart/ListShoppingCart.js
> +                      onClick={() =>
não é uma regra, é só que fica mais organizado

2022-07-20 21:03 UTC, Flavioasjr commented on src/features/shoppingCartIsShowSlice.js
> +  name: 'shoppingCartIsShow',
Obrigado, alteração feita.

2022-07-20 21:10 UTC, Flavioasjr commented on src/features/productsInCartSlice.js
> +      prepare(product) {
No prepare se pode alterar os valores que vão para reducer/action. Por exemplo, nesse caso é adicionada a chave 'quantity', ao objeto product, quando ele é adicionado ao carrinho. FIz isso porque quando tentei fazer diretamente no reducer, dava erro de chave já existe, quando adicionava o mesmo produto duas vezes.

2022-07-20 21:14 UTC, Flavioasjr commented on src/features/productsDataSlice.js
> +  extraReducers(builder) {
Acredito que tenha entendido sim. Cada vez que é feito uma busca numa API, o 'createAsyncThunk' responde com alguns estados. Nesse 'extraReducers' é verificado em qual estado se encontra essa comunicação. Ai usei a chave status, para poder inserir o 'loading' enquanto o estado estar 'pending'. Se o estado for 'fulfilled', os dados são adicionados no state. E se for 'rejected' é lançado um erro.
Acredito que bem resumidamente seja isso.

2022-07-20 21:15 UTC, Flavioasjr commented on src/features/productsDataSlice.js
> +      (product) => product.category !== 'electronics'
É só por conta do tipo do site, como tinha mais produtos de roupas e artigos, deixei a categoria electronics de fora.

2022-07-20 21:22 UTC, Flavioasjr commented on src/features/productsDataSlice.js
> +  name: 'productsData',
Alteração feita!

2022-07-20 21:24 UTC, Flavioasjr commented on src/features/productsDataSlice.js
> +import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
Eu li toda a parte principal da documentação, vi alguns exemplos do redux puro. Mas logo após esses exemplos já é recomendável usar o toolkit, e o exemplo que fiz antes de implementar no projeto foi com toolkit. Aí eu tinha entendido melhor dessa forma.

2022-07-20 21:28 UTC, Flavioasjr commented on build/asset-manifest.json
> -    "main.js": "/Shopping-Cart/static/js/main.efbd505e.js",
Essa parte do build eu ainda não entendo bem. Só fiz para entender um recurso do redux, de verificar se quando um state é mudado, os componentes corretos são atualizados. Para não atualizar componentes sem necessidade.

2022-07-20 22:34 UTC, kaueburiti commented on src/features/productsInCartSlice.js
> +      prepare(product) {
hmm isso não deveria ser necessário, tem cheiro de gambiarra, mas vamos pra frente haha

2022-07-20 22:35 UTC, kaueburiti commented on build/asset-manifest.json
> -    "main.js": "/Shopping-Cart/static/js/main.efbd505e.js",
>  Só fiz para entender um recurso do redux, de verificar se quando um state é mudado, os componentes corretos são atualizados.

Não entendi o que você quis dizer aqui.

Mas basicamente tudo o que está em build são arquivos gerados automaticamente e de maneira otimizada para quando é dado deploy no seu projeto.

2022-07-20 23:45 UTC, Flavioasjr commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
Verdade, foi vacilo meu mesmo. Vou implementar agora.

2022-07-21 00:09 UTC, Flavioasjr commented on src/components/Spinner/styledSpinner.js
> +  color: ${bluePrimaryColor};
Alteração feita

2022-07-21 00:30 UTC, Flavioasjr commented on src/components/ListShoppingCart/ListShoppingCart.js
> +                      onClick={() =>
Alteração feita

2022-07-21 11:46 UTC, kaueburiti approved these changes

2022-07-21 12:48 UTC, Flavioasjr commented on build/asset-manifest.json
> -    "main.js": "/Shopping-Cart/static/js/main.efbd505e.js",
A tag profiler no DevTolls só foi ativada com o build do projeto. Eu vi na documentação do redux, que podemos verificar quais componentes são atualizado depois de determinada ação for feita. Fiz só para testar e ver como funcionava.

2022-07-30 01:02 UTC, merged